### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'Succeeded' of undefined on Typescript 1.5.3

### ISSUE THREAD

**Issue by thakerng** [andreypopp/typescript-loader#24]
Typescript Loader doesn't work on Typescript 1.5.3

```
[02:24:59] [webpack] Hash: f846dfff7e40e9e091ae
Version: webpack 1.10.5
Time: 2694ms
     Asset       Size  Chunks             Chunk Names
index.html  258 bytes          [emitted]  

ERROR in ./src/app/main.ts
Module build failed: TypeError: Cannot read property 'Succeeded' of undefined
    at TypeScriptWebpackHost.<anonymous> (/Users/thakerng/Desktop/nfsolution/phatra2/node_modules/typescript-loader/lib/TypeScriptWebpackHost.js:210:61)
    at tryCatcher (/Users/thakerng/Desktop/nfsolution/phatra2/node_modules/typescript-loader/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/thakerng/Desktop/nfsolution/phatra2/node_modules/typescript-loader/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/Users/thakerng/Desktop/nfsolution/phatra2/node_modules/typescript-loader/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromiseAtPostResolution (/Users/thakerng/Desktop/nfsolution/phatra2/node_modules/typescript-loader/node_modules/bluebird/js/main/promise.js:244:10)
    at Async._drainQueue (/Users/thakerng/Desktop/nfsolution/phatra2/node_modules/typescript-loader/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/thakerng/Desktop/nfsolution/phatra2/node_modules/typescript-loader/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/thakerng/Desktop/nfsolution/phatra2/node_modules/typescript-loader/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

**Comment by mendieta** [comment]
Same issue here

```
webpack result is served from /
content is served from ./public                                                                                                                                                                                                 Hash: 656650354eb1cab777a6                
Version: webpack 1.11.0
Time: 640ms
chunk    {0} js/app.bundle.js (app) 28 bytes {1} [rendered]
    [0] multi app 28 bytes {0} [built] [1 error]
chunk    {1} js/vendor.bundle.js (vendor) 0 bytes [rendered]

ERROR in ./src/index.ts
Module build failed: TypeError: Cannot read property 'Succeeded' of undefined
    at TypeScriptWebpackHost.<anonymous> (/Users/mendieta/Desktop/FOO/LIBRARIES/ts/node_modules/typescript-loader/lib/TypeScriptWebpackHost.js:209:61)
    at tryCatcher (/Users/mendieta/Desktop/FOO/LIBRARIES/ts/node_modules/typescript-loader/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/mendieta/Desktop/FOO/LIBRARIES/ts/node_modules/typescript-loader/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/Users/mendieta/Desktop/FOO/LIBRARIES/ts/node_modules/typescript-loader/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromiseAtPostResolution (/Users/mendieta/Desktop/FOO/LIBRARIES/ts/node_modules/typescript-loader/node_modules/bluebird/js/main/promise.js:244:10)
    at Async._drainQueue (/Users/mendieta/Desktop/FOO/LIBRARIES/ts/node_modules/typescript-loader/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/mendieta/Desktop/FOO/LIBRARIES/ts/node_modules/typescript-loader/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/mendieta/Desktop/FOO/LIBRARIES/ts/node_modules/typescript-loader/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
 @ multi app
```

**Comment by thakerng** [comment]
It seems this project no support anymore I changed to https://github.com/jbrantly/ts-loader
