### ISSUE TITLE
Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by quantuminformation** [andreypopp/typescript-loader#25]
I am working on a RTS game for the web but I am having an issue with webpack and the typescript-loader when running webpack. My project is here: https://github.com/QuantumInformation/Density-Wars

Here is the stacktrace:

```
nmac:Density-Wars nikos$ webpack 
Hash: 62190bf4c04297c7337c
Version: webpack 1.11.0
Time: 485ms
              Asset     Size  Chunks             Chunk Names
    density-wars.js  1.63 kB       0  [emitted]  main
density-wars.js.map  1.44 kB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built] [1 error]
    + 1 hidden modules

ERROR in ./game.ts
Module build failed: TypeError: Cannot read property 'text' of undefined
    at Object.getLength (/Users/nikos/WebstormProjects/Density-Wars/node_modules/typescript-loader/lib/TypeScriptWebpackHost.js:65:18)
    at createLanguageServiceSourceFile (/Users/nikos/WebstormProjects/Density-Wars/node_modules/typescript-loader/node_modules/typescript/bin/typescript.js:36827:97)
    at acquireOrUpdateDocument (/Users/nikos/WebstormProjects/Density-Wars/node_modules/typescript-loader/node_modules/typescript/bin/typescript.js:36938:34)
    at Object.acquireDocument (/Users/nikos/WebstormProjects/Density-Wars/node_modules/typescript-loader/node_modules/typescript/bin/typescript.js:36927:20)
    at Object.getOrCreateSourceFile [as getSourceFile] (/Users/nikos/WebstormProjects/Density-Wars/node_modules/typescript-loader/node_modules/typescript/bin/typescript.js:37482:41)
    at findSourceFile (/Users/nikos/WebstormProjects/Density-Wars/node_modules/typescript-loader/node_modules/typescript/bin/typescript.js:30043:33)
    at processSourceFile (/Users/nikos/WebstormProjects/Density-Wars/node_modules/typescript-loader/node_modules/typescript/bin/typescript.js:30004:27)
    at /Users/nikos/WebstormProjects/Density-Wars/node_modules/typescript-loader/node_modules/typescript/bin/typescript.js:30084:17
    at Object.forEach (/Users/nikos/WebstormProjects/Density-Wars/node_modules/typescript-loader/node_modules/typescript/bin/typescript.js:748:30)
    at processReferencedFiles (/Users/nikos/WebstormProjects/Density-Wars/node_modules/typescript-loader/node_modules/typescript/bin/typescript.js:30082:16)
    at findSourceFile (/Users/nikos/WebstormProjects/Density-Wars/node_modules/typescript-loader/node_modules/typescript/bin/typescript.js:30058:25)
    at processSourceFile (/Users/nikos/WebstormProjects/Density-Wars/node_modules/typescript-loader/node_modules/typescript/bin/typescript.js:30004:27)
    at processRootFile (/Users/nikos/WebstormProjects/Density-Wars/node_modules/typescript-loader/node_modules/typescript/bin/typescript.js:29990:13)
    at /Users/nikos/WebstormProjects/Density-Wars/node_modules/typescript-loader/node_modules/typescript/bin/typescript.js:29869:56
    at Object.forEach (/Users/nikos/WebstormProjects/Density-Wars/node_modules/typescript-loader/node_modules/typescript/bin/typescript.js:748:30)
    at Object.createProgram (/Users/nikos/WebstormProjects/Density-Wars/node_modules/typescript-loader/node_modules/typescript/bin/typescript.js:29869:12)
    at synchronizeHostData (/Users/nikos/WebstormProjects/Density-Wars/node_modules/typescript-loader/node_modules/typescript/bin/typescript.js:37411:33)
    at Object.getEmitOutput (/Users/nikos/WebstormProjects/Density-Wars/node_modules/typescript-loader/node_modules/typescript/bin/typescript.js:40181:13)
    at TypeScriptWebpackHost.emit (/Users/nikos/WebstormProjects/Density-Wars/node_modules/typescript-loader/lib/TypeScriptWebpackHost.js:203:20)
    at Object.typescriptLoader (/Users/nikos/WebstormProjects/Density-Wars/node_modules/typescript-loader/lib/index.js:36:40)
 @ multi main
```

Thanks for any advice.

**Comment by QuantumInformation** [comment]
using awesome-typescript-loader
